server:
  port: 5000
  servlet:
    context-path: /feature--toggle


ff4j:
  api:
    spring-doc:
      enabled: true

security:
  username: dev
  password: devpass01

#Configurações actuator
management:
  server:
    port: 9090
