server:
  port: 5000
  servlet:
    context-path: /feature--toggle


ff4j:
  api:
    spring-doc:
      enabled: true

security:
  username: ${ACCESS_USERNAME:admin}
  password: ${ACCESS_PASSWORD:admin}
